[package]
name = "api"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
axum = "0.8.9"
tokio = { version = "1.53.2", features = ["macros", "rt-multi-thread"] }

[lints]
workspace = true

[dev-dependencies]
tower = { version = "0.5.3", features = ["util"] }
